name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Optionally, disable strict host key checking for first-time connections
          touch ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.HOST_DNS }} >> ~/.ssh/known_hosts

      - name: Copy index.html to EC2
        run: |
          scp -o StrictHostKeyChecking=no index.html ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/html/index.html
